version: '3'
services:
  e2e-chrome:
    image: cypresss-qa-demos:latest
    command:
      - "chrome"
    volumes:
      - ./allure-t:/cypress-docker/allure-results
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/screenshots:/cypress-docker/cypress/screenshots
  e2e-firefox:
    image: cypresss-qa-demos:latest
    command:
      - "firefox"
    volumes:
      - ./allure-t:/cypress-docker/allure-results
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/screenshots:/cypress-docker/cypress/screenshots
  e2e-edge:
    image: cypresss-qa-demos:latest
    command:
        - "edge"
    volumes:
      - ./allure-t:/cypress-docker/allure-results
      - ./cypress/videos:/cypress-docker/cypress/videos
      - ./cypress/screenshots:/cypress-docker/cypress/screenshots